buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:7.4.2'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

defaultConfig {
        applicationId "com.retro.subsonic"
        minSdk 16
        targetSdk 28
        versionCode 3
        versionName "1.0.2"
    }
